# numpy

numpy在数组的存储于输入输出效率远远高于python中的数组
numpy与C语言写成，执行效率高效


In [1]:
import numpy as np
# numpy不使用循环，有arange方法
print(np.arange(5)**2)

[ 0  1  4  9 16]


In [3]:
print([1,2,3,4])
# numpy中标示数组方式有所不同

[1, 2, 3, 4]


In [7]:
# x = input("ipynb")
# 无法进行读入操作

1. 数组对象ndarray



In [43]:
a = np.arange(5)  #返回数组对象
b = np.array([[1,2.0],[5,2]])
print(b[1,1],a)
b.dtype #全部自动转换数据类型

2.0 [0 1 2 3 4]


dtype('float64')

In [37]:
m = np.array([np.arange(2),np.arange(2)])
# 创建多维数组
m[1]

array([0, 1])


| bool | 用一位存储的布尔类型（值为 TRUE 或 FALSE ）|
| ----- | ----- |
| inti | 由所在平台决定其精度的整数（一般为 int32 或 int64 ） |
int8|整数，范围为128至127|
|int16|整数，范围为32 768至32 767|
|int32|整数，范围为2 31 至2 31 1|
|int64|整数，范围为2 63 至2 63 1|
|uint8|无符号整数，范围为0至255|
|uint16|无符号整数，范围为0至65 535|
|uint32|无符号整数，范围为0至2 32 1|
|uint64|无符号整数，范围为0至2 64 1|
|float16|半精度浮点数（16位）：其中用1位表示正负号，5位表示指数，10位表示尾数|
|float32|单精度浮点数（32位）：其中用1位表示正负号，8位表示指数，23位表示尾数|
|complex64|复数，分别用两个32位浮点数表示实部和虚部|

In [44]:
a = np.arange(9)
a[3:7] #索引

array([3, 4, 5, 6])

In [50]:
a1 = a[:7:2]
a1 #默认从零开始，步长为2
a2 = a[1: : 2]
a2 #默认到最后
a[::-1] #翻转数组

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
muti = np.arange(24).reshape(2,3,4) #改变维度2*3*4
remuti = muti[::-1,::-1,::-1]
print(muti,"\n","-----"*3,"\n",remuti)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
 --------------- 
 [[[23 22 21 20]
  [19 18 17 16]
  [15 14 13 12]]

 [[11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]


In [63]:
one = muti.ravel()
#  flatten 就是展平的意思，与 ravel 函数的功能相同。
# 不过， flatten 函数会请求分配内存来保存结果，而 ravel 函数只是返回数组的一个视图
one #降维展平

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
one.shape= (4,6)
 # resize resize 和 reshape 函数的功能一样，但 resize 会直接修改所操作的数组
one.reshape(6,4)  #重新分配

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
one.transpose() #矩阵转置

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [ ]:
import scipy as sp
imgCat = sp.imag('cat.jpg')